# This file was generated by GoReleaser. DO NOT EDIT.
cask "drillback" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9e978077322b63617aa48f152a14893e907edb379e106a6e91d3a8398d0b93fd"
      url "https://github.com/spelingbee/drillback/releases/download/v0.1.0/drillback_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a005387cb5a62b72e8be475c4494a1c85544faf6f4ca6d0878215246e2a499dd"
      url "https://github.com/spelingbee/drillback/releases/download/v0.1.0/drillback_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "31aa64c43df07122027ff9513d32045954e6b6634b442a5b15fa35d81fe7de7b"
      url "https://github.com/spelingbee/drillback/releases/download/v0.1.0/drillback_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e76c191bc3b728e8ad7d7d5252c188c2fb6178580334a48db67ffa0775440e6"
      url "https://github.com/spelingbee/drillback/releases/download/v0.1.0/drillback_#{version}_linux_amd64.tar.gz"
    end
  end

  name "drillback"
  desc "Prove a backup restores, by restoring it into a throwaway stack."
  homepage "https://github.com/spelingbee/drillback"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drillback"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/drillback"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    drillback needs a Docker daemon, and restic for restic sources:
      brew install restic
      # plus Docker Desktop, colima, or any daemon DOCKER_HOST points at
    Start with:
      drillback check --recipe gitea --source restic --from /path/to/repo
  EOS
end
